name: Publish Docker image

on:
  push:
    branches:
      - "main"

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build image and push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: tythos/rando:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
